[platformio]
src_dir = .

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_protocol = usbtiny
upload_flags =
    -B 32
monitor_speed = 115200
lib_deps = arduino-libraries/Servo@^1.2.1

